In [1]:
import numpy as np

<h2>The Basics</h2>

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([[2.0, 3.1, 4.2], [4.5, 5.6, 6.7]])
print(b)

[[2.  3.1 4.2]
 [4.5 5.6 6.7]]


In [4]:
#Get Dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
#Get Shape
b.shape

(2, 3)

<h2>Accessing specific elements, rows, columns</h2>

In [7]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
#Get a specific element [r, c]
a[1,3]

9

In [10]:
#Get specific row
a[1, :]

array([ 6,  7,  8,  9, 10])

In [11]:
#Get specific column
a[:, 2]

array([3, 8])

In [13]:
# [startindex: endindex+1: stepsize]
a[0, 1:4:1]

array([2, 3, 4])

<h2>Initializing Different Arrays</h2>

In [15]:
#All 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#All 1's matrix
np.ones((4,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
#Any other number
np.full((2,2), 100)

array([[100, 100],
       [100, 100]])

In [20]:
#Random decimal values
np.random.rand(2,3)

array([[0.20770281, 0.22192595, 0.76903419],
       [0.51031303, 0.39033439, 0.7828119 ]])

In [23]:
#Random int values
np.random.randint(2,10, size=(2,4))

array([[3, 5, 8, 7],
       [5, 8, 8, 4]])

In [26]:
#Repeat array
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [32]:
output = np.ones([5,5])
print(output)
z = np.zeros([3,3])
z[1,1] = 9
print(z)
output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
#Copying arrays
a = np.array([1,2,3])
b = a.copy()
b[1] = 4
print(b)
print(a)

[1 4 3]
[1 2 3]


<h2>Mathematics</h2>

In [35]:
a = np.array([2,4,6])
print(a)

[2 4 6]


In [36]:
a+2

array([4, 6, 8])

<h3>Linear Algebra</h3>

In [40]:
a = np.ones([2,3])
print(a)
b = np.full([3,4], 4)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


array([[12., 12., 12., 12.],
       [12., 12., 12., 12.]])

In [41]:
#Finding determinant
c = np.identity(4)
np.linalg.det(c)

1.0

<h3>Statistics</h3>

In [42]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.min(stats, axis=1)

array([1, 4])

In [45]:
np.max(stats)

6

In [46]:
np.sum(stats)

21

<h3>Reorganizing Arrays</h3>

In [48]:
before = np.array([[1,2,3], [4,5,6]])
print(before)
after = before.reshape(6,1)
print(after)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [50]:
#Vertically stacking vectors
a = np.array([2,4,6])
b = np.array([3,6,9])
np.vstack([a,b,a,b])

array([[2, 4, 6],
       [3, 6, 9],
       [2, 4, 6],
       [3, 6, 9]])

In [52]:
#Horizontally stacking vectors
d = np.ones((2,3))
e = np.zeros((2,2))
np.hstack((d,e))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

<h3>Load Data from File</h3>

In [59]:
filedata = np.genfromtxt('Note.txt', delimiter=';')
filedata = filedata.astype('int32')
filedata

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

<h3>Boolean Masking and Advanced Indexing</h3>

In [60]:
filedata > 2

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [61]:
filedata[filedata > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [63]:
np.any(filedata > 5, axis=0)

array([ True,  True,  True,  True,  True])

In [65]:
((filedata > 5) & (filedata < 20))

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])