<h1> Welcome to Numpy </h1>

In [2]:
import numpy as np

In [3]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
my_lst1 = [3, 6, 9, 12, 15]
my_lst2 = [4, 8, 12, 16, 20]
my_lst3 = [2, 4, 6, 8, 10]

In [7]:
arr1 = np.array([my_lst1, my_lst2, my_lst3])

In [8]:
arr1

array([[ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 2,  4,  6,  8, 10]])

In [9]:
arr.shape

(5,)

In [10]:
arr1.shape

(3, 5)

In [11]:
arr1.reshape

<function ndarray.reshape>

In [12]:
arr1.reshape(5,3)

array([[ 3,  6,  9],
       [12, 15,  4],
       [ 8, 12, 16],
       [20,  2,  4],
       [ 6,  8, 10]])

In [13]:
arr1.shape

(3, 5)

<h2> Indexing </h2>

In [14]:
arr1[:,:]

array([[ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 2,  4,  6,  8, 10]])

In [15]:
arr1[0:2, 3:]

array([[12, 15],
       [16, 20]])

In [16]:
arr2 = np.arange(0, 10)

In [17]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr2 = np.arange(0, 10, 2)
arr2

array([0, 2, 4, 6, 8])

In [19]:
arr2[3:] = 100
arr2

array([  0,   2,   4, 100, 100])

In [20]:
arr3 = arr2.copy()
arr3

array([  0,   2,   4, 100, 100])

In [21]:
arr3[3:] = 1000
arr3

array([   0,    2,    4, 1000, 1000])

In [22]:
arr2 < 10

array([ True,  True,  True, False, False])

In [23]:
arr3 % 3

array([0, 2, 1, 1, 1], dtype=int32)

In [24]:
arr3 % 2

array([0, 0, 0, 0, 0], dtype=int32)

<h2> In-built functions </h2>

In [25]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
np.random.rand(2,3)

array([[0.00313727, 0.69422487, 0.08861299],
       [0.26404712, 0.48566442, 0.36352179]])

In [27]:
np.random.rand(0, 50, 8)

array([], shape=(0, 50, 8), dtype=float64)

In [29]:
np.random.randint(0, 50, 8).reshape(2, 4)

array([[ 6, 14,  8, 14],
       [30, 16, 42,  9]])

In [30]:
np.random.random_sample((3,5))

array([[0.53464945, 0.01668289, 0.11132398, 0.24642629, 0.36769583],
       [0.31052289, 0.51881166, 0.7915068 , 0.34469515, 0.25642185],
       [0.6833382 , 0.94922988, 0.14552812, 0.98266249, 0.15990445]])